// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Charge struct {
	ID        string
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type InstallationCharge struct {
	InstallationID string
	ChargeID       pgtype.Text
}
